/**
 * @napplet/services — Shared types for reference service implementations.
 *
 * These types describe the internal state that services manage and expose
 * to the shell host via callbacks. They are NOT NIP-01 wire types.
 */

// ─── Audio Service Types ──────────────────────────────────────────────────

/**
 * An active audio source registered by a napplet.
 *
 * @example
 * ```ts
 * const source: AudioSource = {
 *   windowId: 'win-1',
 *   nappClass: 'music-player',
 *   title: 'Now Playing',
 *   muted: false,
 * };
 * ```
 */
export interface AudioSource {
  /** The napplet window that registered this audio source. */
  windowId: string;
  /** The napp class/type (e.g., 'music-player'). */
  nappClass: string;
  /** Human-readable title for the audio source. */
  title: string;
  /** Whether this source is currently muted. */
  muted: boolean;
}

/**
 * Options for creating an audio service via createAudioService().
 *
 * @example
 * ```ts
 * const audioService = createAudioService({
 *   onChange: (sources) => console.log('Audio sources changed:', sources.size),
 * });
 * ```
 */
export interface AudioServiceOptions {
  /**
   * Called when the audio source registry changes (register, unregister,
   * mute, state update). The shell host uses this to update UI.
   */
  onChange?: (sources: ReadonlyMap<string, AudioSource>) => void;
}

// ─── Notification Service Types ───────────────────────────────────────────

/**
 * A notification created by a napplet.
 *
 * @example
 * ```ts
 * const notification: Notification = {
 *   id: 'notif-1',
 *   windowId: 'win-1',
 *   title: 'New Message',
 *   body: 'You have a new message from Alice',
 *   read: false,
 *   createdAt: 1711800000,
 * };
 * ```
 */
export interface Notification {
  /** Unique notification identifier (generated by the service). */
  id: string;
  /** The napplet window that created this notification. */
  windowId: string;
  /** Short notification title. */
  title: string;
  /** Notification body/description. */
  body: string;
  /** Whether the notification has been read/acknowledged. */
  read: boolean;
  /** Unix timestamp (seconds) when the notification was created. */
  createdAt: number;
}

/**
 * Options for creating a notification service via createNotificationService().
 *
 * @example
 * ```ts
 * const notifService = createNotificationService({
 *   onChange: (notifications) => console.log('Notifications:', notifications.length),
 *   maxPerWindow: 50,
 * });
 * ```
 */
export interface NotificationServiceOptions {
  /**
   * Called when the notification list changes (create, dismiss, read).
   * The shell host uses this to update UI (toast, badge, etc.).
   */
  onChange?: (notifications: readonly Notification[]) => void;
  /**
   * Maximum notifications to retain per window. Oldest are evicted
   * when the limit is exceeded. Default: 100.
   */
  maxPerWindow?: number;
}
